### ISSUE TITLE
Enabling DeepSpeed with fp16 crashes

### ISSUE THREAD

**Issue by dan1elherbst** [TUM-DI-Lab-Graph-Scaling/ocp#2]
I tried getting DeepSpeed running the *s2ef* task running with the *cgcnn* model (using my latest commit on the `deepspeed` branch). Using the code as is (i.e. using the plain DeepSpeed trainer without any optimization) works. 
However, using the following DeepSpeed config file:

```json
{
  "train_batch_size": 32,
  "gradient_accumulation_steps": 1,
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.0005
    }
  },
  "fp16": {
    "enabled": true
  },
  "zero_optimization": false
}
```

where the fp16 optimization is enabled, and running the job on one GPU for now as follows:

```console
(ocp-models) [dherbst@kanon ocp]$ python -u -m torch.distributed.launch --nproc_per_node=1 main.py --distributed --num-gpus 1 --mode train --config-yml configs/s2ef/200k/cgcnn/cgcnn.yml --deepspeed-mode deepspeed-optimizer --deepspeed-config configs/s2ef/200k/cgcnn/ds_config.json
```

results in the following error:

```console
Traceback (most recent call last):
  File "/home/dherbst/tum-di-lab/OCP-Baseline/ocp/main.py", line 128, in <module>
    Runner()(config)
  File "/home/dherbst/tum-di-lab/OCP-Baseline/ocp/main.py", line 68, in __call__
    self.task.run()
  File "/home/dherbst/tum-di-lab/OCP-Baseline/ocp/ocpmodels/tasks/task.py", line 56, in run
    raise e
  File "/home/dherbst/tum-di-lab/OCP-Baseline/ocp/ocpmodels/tasks/task.py", line 49, in run
    self.trainer.train(
  File "/home/dherbst/tum-di-lab/OCP-Baseline/ocp/ocpmodels/trainers/forces_trainer.py", line 330, in train
    out = self._forward(batch)
  File "/home/dherbst/tum-di-lab/OCP-Baseline/ocp/ocpmodels/trainers/forces_trainer.py", line 432, in _forward
    out_energy, out_forces = self.model(batch_list)
  File "/home/dherbst/miniconda3/envs/ocp-models/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dherbst/miniconda3/envs/ocp-models/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/dherbst/miniconda3/envs/ocp-models/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1616, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/dherbst/miniconda3/envs/ocp-models/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dherbst/tum-di-lab/OCP-Baseline/ocp/ocpmodels/common/data_parallel.py", line 59, in forward
    return self.module(batch_list[0].to(f"cuda:{self.device_ids[0]}"))
  File "/home/dherbst/miniconda3/envs/ocp-models/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dherbst/tum-di-lab/OCP-Baseline/ocp/ocpmodels/models/cgcnn.py", line 165, in forward
    energy = self._forward(data)
  File "/home/dherbst/tum-di-lab/OCP-Baseline/ocp/ocpmodels/common/utils.py", line 121, in cls_method
    return f(self, *args, **kwargs)
  File "/home/dherbst/miniconda3/envs/ocp-models/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/dherbst/tum-di-lab/OCP-Baseline/ocp/ocpmodels/models/cgcnn.py", line 154, in _forward
    mol_feats = self._convolve(data)
  File "/home/dherbst/tum-di-lab/OCP-Baseline/ocp/ocpmodels/models/cgcnn.py", line 185, in _convolve
    node_feats = self.embedding_fc(data.x)
  File "/home/dherbst/miniconda3/envs/ocp-models/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dherbst/miniconda3/envs/ocp-models/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/dherbst/miniconda3/envs/ocp-models/lib/python3.9/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: expected scalar type Half but found Float
```

**Comment by d-stoll** [comment]
Change Tensors in models manually to half precision. Maybe look again at https://pytorch.org/docs/stable/amp.html#cuda-ops-that-can-autocast-to-float16 (torch.autocast) to automatically cast tensors.

**Comment by dan1elherbst** [comment]
https://github.com/microsoft/DeepSpeed/issues/550
